---

- name: Get MariaDB APT key
  apt_key:
    keyserver: "{{ mariadb_apt_keyserver }}"
    id: "{{ mariadb_apt_key }}"
  when: mariadb_install_from_official_repo

- name: Configure MariaDB official APT repository
  apt_repository:
    repo: 'deb [arch=amd64] {{ mariadb_apt_mirror }}/MariaDB/repo/{{ mariadb_version }}/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} main'
    filename: mariadb
  when: mariadb_install_from_official_repo

- name: Install MariaDB
  apt:
    name:
    - "mariadb-server-{{ mariadb_version }}"
    - "mariadb-client-{{ mariadb_version }}"
  tags: mysql.install

- name: Install python-mysqldb (for Ansible)
  apt:
    name: python-mysqldb
  tags: mysql.install

- name: Create databases
  mysql_db:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ mysql_databases }}"
  tags: mysql.dbs

- name: Add users
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost') }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ mysql_users }}"
  tags: mysql.users

- name: Set MySQL options
  ini_file:
    path: /etc/mysql/my.cnf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items: "{{ mysql_options }}"
  notify: restart mysql
  tags: mysql.options

- name: Enable and start MySQL service
  tags: mysql.install
  systemd:
    name: mysql.service
    enabled: true
    state: started
